(()=>{
'use strict';
const wheel=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const KEY='rouletteTrackerV2';
const $=id=>document.getElementById(id);
const el={tableSel:$('tableSel'),undoBtn:$('undoBtn'),resetBtn:$('resetBtn'),tableTitle:$('tableTitle'),coupCount:$('coupCount'),storageText:$('storageText'),sessionInfo:$('sessionInfo'),initBtn:$('initBtn'),liveBtn:$('liveBtn'),statusText:$('statusText'),betsText:$('betsText'),plText:$('plText'),aNum:$('aNum'),bNum:$('bNum'),aScore:$('aScore'),bScore:$('bScore'),betActions:$('betActions'),betABtn:$('betABtn'),betABBtn:$('betABBtn'),skipBtn:$('skipBtn'),openBet:$('openBet'),openBetText:$('openBetText'),feedback:$('feedback'),hitsText:$('hitsText'),rateText:$('rateText'),history:$('history'),initPanel:$('initPanel'),livePanel:$('livePanel'),numGrid:$('numGrid'),pendingDisplay:$('pendingDisplay'),pendingHint:$('pendingHint'),clearPendingBtn:$('clearPendingBtn'),liveUndoBtn:$('liveUndoBtn'),newSessionBtn:$('newSessionBtn'),exportBtn:$('exportBtn')};
let persistent=true,pending='',pendingTimer=null,inputLocked=false;
const freshTable=i=>({name:'Tisch '+(i+1),history:[],bets:[],activeBet:null,skips:0,signals:[],mode:'init',sessionStarted:new Date().toISOString()});
const freshState=()=>({active:0,tables:[freshTable(0),freshTable(1),freshTable(2)]});
function storageOK(){try{localStorage.setItem('__rt_test__','1');localStorage.removeItem('__rt_test__');return true}catch(e){return false}}
persistent=storageOK();let state=freshState();
if(persistent){try{state=JSON.parse(localStorage.getItem(KEY))||freshState()}catch(e){state=freshState();persistent=false}}
if(!state||!Array.isArray(state.tables))state=freshState();while(state.tables.length<3)state.tables.push(freshTable(state.tables.length));
function sectorForCenter(center){const i=wheel.indexOf(Number(center));if(i<0)return[];const a=[];for(let d=-3;d<=3;d++)a.push(wheel[(i+d+37)%37]);return a}
function repairTable(t,i){t.name=t.name||'Tisch '+(i+1);t.history=Array.isArray(t.history)?t.history.filter(n=>Number.isInteger(n)&&n>=0&&n<=36):[];t.bets=Array.isArray(t.bets)?t.bets:[];t.signals=Array.isArray(t.signals)?t.signals:[];t.mode=t.mode==='live'?'live':'init';t.skips=Number(t.skips)||0;t.sessionStarted=t.sessionStarted||new Date().toISOString();t.bets.forEach(b=>{if(!Array.isArray(b.numbers)){const a=sectorForCenter(b.aCenter),bb=sectorForCenter(b.bCenter);b.numbers=b.type==='AB'?[...new Set([...a,...bb])]:a}b.units=Number(b.units)||b.numbers.length});t.signals.forEach(s=>{if(!Array.isArray(s.numbersA))s.numbersA=sectorForCenter(s.aCenter);if(!Array.isArray(s.numbersAB))s.numbersAB=[...new Set([...s.numbersA,...sectorForCenter(s.bCenter)])]});if(t.activeBet&&!Array.isArray(t.activeBet.numbers)){const found=t.bets.find(b=>b.id===t.activeBet.id);t.activeBet=found||null}}
state.tables.forEach(repairTable);state.active=Number.isInteger(state.active)&&state.active>=0&&state.active<3?state.active:0;
function save(){if(!persistent)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){persistent=false}}
function sectorAt(i){const a=[];for(let d=-3;d<=3;d++)a.push(wheel[(i+d+37)%37]);return a}
function zScore(history,sector,n){const data=history.slice(-Math.min(n,history.length)),N=data.length;if(!N)return 0;const S=new Set(sector),hits=data.filter(v=>S.has(v)).length,p=7/37,sd=Math.sqrt(N*p*(1-p));return sd?(hits-N*p)/sd:0}
function score(history,i){const sector=sectorAt(i),wins=[15,30,60],weights=[.7,1,1.3];let total=0,weight=0;wins.forEach((n,j)=>{if(Math.min(n,history.length)>=10){total+=zScore(history,sector,n)*weights[j];weight+=weights[j]}});return{center:wheel[i],sector,score:weight?total/weight:-999}}
function topTwo(history){const arr=wheel.map((_,i)=>score(history,i)).sort((a,b)=>b.score-a.score),a=arr[0];return[a,arr.find(x=>x.center!==a.center&&x.sector.every(n=>!a.sector.includes(n)))||arr[1]]}
function signalLevel(s,n){return n<15?0:s<1.2?0:s<1.8?1:s<2.4?2:s<3?3:4}
function currentSignal(t){const s=t.signals[t.signals.length-1];return s&&!s.resolved?s:null}
function createSignal(t){if(t.history.length<15)return null;const old=currentSignal(t);if(old&&old.atCoup===t.history.length)return old;const[a,b]=topTwo(t.history),s={id:Date.now()+Math.random(),atCoup:t.history.length,createdAt:new Date().toISOString(),aCenter:a.center,bCenter:b.center,aScore:a.score,bScore:b.score,level:signalLevel(a.score,t.history.length),numbersA:[...a.sector],numbersAB:[...new Set([...a.sector,...b.sector])],resolved:false,result:null,hitA:null,hitAB:null,played:null,skipped:false};t.signals.push(s);return s}
function resolveSignal(t,n){const s=currentSignal(t);if(!s)return;const a=Array.isArray(s.numbersA)?s.numbersA:sectorForCenter(s.aCenter),ab=Array.isArray(s.numbersAB)?s.numbersAB:[...new Set([...a,...sectorForCenter(s.bCenter)])];s.numbersA=a;s.numbersAB=ab;s.result=n;s.hitA=a.includes(n);s.hitAB=ab.includes(n);s.resolved=true;s.resolvedAt=new Date().toISOString()}
function resolveBet(t,n){if(!t.activeBet)return;const b=t.bets.find(x=>x.id===t.activeBet.id)||t.activeBet;if(!Array.isArray(b.numbers)){const a=sectorForCenter(b.aCenter),bb=sectorForCenter(b.bCenter);b.numbers=b.type==='AB'?[...new Set([...a,...bb])]:a}b.units=Number(b.units)||b.numbers.length;b.result=n;b.hit=b.numbers.includes(n);b.resolved=true;b.resolvedAt=new Date().toISOString();t.activeBet=null}
function betPL(b){return !b.resolved?0:b.hit?36-(Number(b.units)||0):-(Number(b.units)||0)}
function stats(t){const r=t.bets.filter(b=>b.resolved),hits=r.filter(b=>b.hit).length,p=r.reduce((s,b)=>s+betPL(b),0);return{r,hits,p,rate:r.length?hits/r.length*100:0}}
function addNumber(n){if(inputLocked||!Number.isInteger(n)||n<0||n>36)return;inputLocked=true;try{const t=state.tables[state.active];if(t.mode==='live'){try{resolveSignal(t,n)}catch(e){console.error('signal resolve',e)}try{resolveBet(t,n)}catch(e){console.error('bet resolve',e);t.activeBet=null}}t.history.push(n);if(t.mode==='live')createSignal(t);save();render()}finally{inputLocked=false}}
function createBet(type){const t=state.tables[state.active];if(t.mode!=='live'||t.activeBet||t.history.length<15)return;const[a,b]=topTwo(t.history),numbers=type==='A'?[...a.sector]:[...new Set([...a.sector,...b.sector])],sig=createSignal(t),bet={id:Date.now()+Math.random(),type,createdAt:new Date().toISOString(),aCenter:a.center,bCenter:type==='AB'?b.center:null,numbers,units:numbers.length,resolved:false,hit:false,result:null,signalId:sig?sig.id:null};t.bets.push(bet);t.activeBet=bet;if(sig)sig.played=type;save();render()}
function skip(){const t=state.tables[state.active];if(t.mode!=='live')return;const s=createSignal(t);t.skips++;if(s)s.skipped=true;save();render()}
function clearPendingInput(){pending='';if(pendingTimer){clearTimeout(pendingTimer);pendingTimer=null}renderPending()}
function renderPending(msg){el.pendingDisplay.textContent=pending||'—';el.pendingHint.textContent=msg||(pending?'zweite Ziffer oder kurz warten':'Nächste Zahl')}
function commitPending(){if(pending==='')return;const n=Number(pending);pending='';pendingTimer=null;renderPending();addNumber(n)}
function digit(d){if(inputLocked)return;if(pendingTimer){clearTimeout(pendingTimer);pendingTimer=null}if(pending===''){if(d===0||d>=4){addNumber(d);return}pending=String(d);renderPending();pendingTimer=setTimeout(commitPending,650);return}const combo=Number(pending+String(d));pending='';renderPending();if(combo>=10&&combo<=36)addNumber(combo);else{renderPending('Ungültig – neu eingeben');setTimeout(()=>renderPending(),450)}}
function setMode(mode){const t=state.tables[state.active];t.mode=mode;clearPendingInput();if(mode==='live')createSignal(t);save();render()}
function undo(){const t=state.tables[state.active];clearPendingInput();if(t.activeBet){const id=t.activeBet.id;t.activeBet=null;const b=t.bets.find(x=>x.id===id&&!x.resolved);if(b)t.bets=t.bets.filter(x=>x!==b);const s=currentSignal(t);if(s)s.played=null;save();render();return}if(!t.history.length)return;if(t.mode==='live'){const s=currentSignal(t);if(s&&s.atCoup===t.history.length)t.signals.pop()}t.history.pop();if(t.mode==='live')createSignal(t);save();render()}
function render(){const t=state.tables[state.active],[a,b]=topTwo(t.history),st=stats(t),lv=signalLevel(a.score,t.history.length);el.storageText.textContent=persistent?'Speicher: dauerhaft':'Speicher: nur diese Sitzung';el.tableSel.value=String(state.active);el.tableTitle.textContent=t.name.toUpperCase();el.coupCount.textContent=t.history.length+' Coups';el.sessionInfo.textContent=new Date(t.sessionStarted).toLocaleDateString('de-DE');el.aNum.textContent=t.history.length>=15?a.center:'—';el.bNum.textContent=t.history.length>=15?b.center:'—';el.aScore.textContent=t.history.length>=15?'Score '+a.score.toFixed(1):'—';el.bScore.textContent=t.history.length>=15?'Score '+b.score.toFixed(1):'—';el.statusText.textContent=t.mode==='init'?'ERFASSEN':t.activeBet?'BET AKTIV':t.history.length<15?'ZU WENIG DATEN':lv>=2?'BET':lv===1?'BEOBACHTEN':'WARTEN';el.betsText.textContent=st.r.length;el.plText.textContent=(st.p>0?'+':'')+st.p+' U';el.plText.className=st.p>0?'positive':st.p<0?'negative':'';el.hitsText.textContent=st.hits+' Hits';el.rateText.textContent=st.rate.toFixed(1).replace('.',',')+'%';if(t.activeBet){el.openBet.classList.remove('hidden');el.betActions.classList.add('hidden');el.openBetText.textContent=t.activeBet.type==='A'?'A · '+t.activeBet.aCenter:'A+B · '+t.activeBet.aCenter+' + '+t.activeBet.bCenter;el.feedback.textContent='Wette bestätigt – jetzt Ergebnis eingeben.';el.feedback.className='feedback warn'}else{el.openBet.classList.add('hidden');el.betActions.classList.toggle('hidden',t.mode!=='live');const last=t.bets.filter(x=>x.resolved).slice(-1)[0];if(last){el.feedback.textContent=last.hit?'✓ HIT · '+(betPL(last)>0?'+':'')+betPL(last)+' U':'✕ MISS · '+betPL(last)+' U';el.feedback.className='feedback '+(last.hit?'positive':'negative')}else{el.feedback.textContent=t.mode==='init'?'Zahlenserie erfassen, danach LIVE wählen.':'Noch kein Bet aktiv.';el.feedback.className='feedback'}}el.history.innerHTML='';t.history.slice(-14).reverse().forEach((n,i)=>{const e=document.createElement('span');e.className='ball'+(i===0?' latest':'');e.textContent=n;el.history.appendChild(e)});el.initPanel.classList.toggle('hidden',t.mode!=='init');el.livePanel.classList.toggle('hidden',t.mode!=='live');el.initBtn.classList.toggle('active',t.mode==='init');el.liveBtn.classList.toggle('active',t.mode==='live');el.betABtn.disabled=el.betABBtn.disabled=!!t.activeBet||t.history.length<15||t.mode!=='live'}
for(let n=0;n<=36;n++){const b=document.createElement('button');b.className='nbtn';b.textContent=n;b.addEventListener('click',()=>addNumber(n));el.numGrid.appendChild(b)}
document.querySelectorAll('[data-k]').forEach(b=>b.addEventListener('click',()=>digit(Number(b.dataset.k))));el.tableSel.addEventListener('change',e=>{state.active=Number(e.target.value);clearPendingInput();save();render()});el.undoBtn.addEventListener('click',undo);el.liveUndoBtn.addEventListener('click',undo);el.resetBtn.addEventListener('click',()=>{if(confirm('Aktuellen Tisch wirklich komplett löschen?')){state.tables[state.active]=freshTable(state.active);clearPendingInput();save();render()}});el.betABtn.addEventListener('click',()=>createBet('A'));el.betABBtn.addEventListener('click',()=>createBet('AB'));el.skipBtn.addEventListener('click',skip);el.initBtn.addEventListener('click',()=>setMode('init'));el.liveBtn.addEventListener('click',()=>setMode('live'));el.clearPendingBtn.addEventListener('click',clearPendingInput);el.newSessionBtn.addEventListener('click',()=>{if(confirm('Neue Session für diesen Tisch starten? Vorher ggf. exportieren.')){state.tables[state.active]=freshTable(state.active);clearPendingInput();save();render()}});el.exportBtn.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='roulette-session-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderPending();render();
})();